### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy; get_numpy = f"numpy=={numpy.__version__}"
    except: get_numpy = "numpy"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    get_vllm, get_triton = ("vllm==0.10.1", "triton==3.2.0") if is_t4 else ("vllm", "triton")
    !uv pip install -qqq --upgrade \
        unsloth {get_vllm} {get_numpy} torchvision bitsandbytes xformers
    !uv pip install -qqq {get_triton}
!uv pip install transformers==4.55.4

### Unsloth

Goal: To convert `Qwen3-4B-Base` into a reasoning model via GRPO by using OpenR1's Math dataset.

We first pre fine-tune the model to make GRPO skip trying to match formatting - this speeds GRPO up.

In [3]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3.5-4B",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = True, # Enable vLLM fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 09-12 13:14:27 [__init__.py:241] Automatically detected platform cuda.
ERROR 09-12 13:14:30 [fa_utils.py:57] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: Patching vLLM to enable standby.
Unsloth: Patching vLLM v1 graph capture
Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2025.9.4: Fast Qwen3 patching. Transformers: 4.55.4. vLLM: 0.10.1.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/Qwen3-4B-Thinking-2507 with actual GPU utilization = 89.15%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.74 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 192.
Unsloth: vLLM's KV Cache can use up to 6.19 GB. Also swap space = 0 GB.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 09-12 13:14:56 [utils.py:326] non-default args: {'model': 'unsloth/Qwen3-4B-Thinking-2507', 'dtype': torch.float16, 'seed': 0, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 0, 'gpu_memory_utilization': 0.8914777596979145, 'max_num_batched_tokens': 2048, 'max_num_seqs': 192, 'max_logprobs': 0, 'disable_log_stats': True, 'enable_lora': True, 'max_lora_rank': 32, 'compilation_config': {"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":null,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":null,"local_cache_dir":null}, 'enable_sleep_mode': True}
INFO 09-12 13:15:21 [__init__.py:711] Resolved architecture: Qwen3ForCausalLM
WARNING 09-12 13:15:21 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
INFO 09-12 13:15:21 [__init__.py:1750] Using max model len 2048
WARNING 09-12 13:15:21 [arg_utils.py:1770] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
INFO 09-12 13:15:23 [llm_engine.py:222] Initializing a V0 LLM engine (v0.10.1) with config: model='unsloth/Qwen3-4B-Thinking-2507', speculative_config=None, tokenizer='unsloth/Qwen3-4B-Thinking-2507', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen3-4B-Thinking-2507, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{"enable_fusion":false,"enable_noop":false},"max_capture_size":192,"local_cache_dir":null}, use_cached_outputs=False,

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/238 [00:00<?, ?B/s]

INFO 09-12 13:15:26 [cuda.py:384] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-12 13:15:26 [cuda.py:433] Using XFormers backend.
INFO 09-12 13:15:27 [parallel_state.py:1134] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 09-12 13:15:27 [model_runner.py:1080] Starting to load model unsloth/Qwen3-4B-Thinking-2507...
INFO 09-12 13:15:28 [weight_utils.py:296] Using model weights format ['*.safetensors']

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.08G [00:00<?, ?B/s]

INFO 09-12 13:18:35 [weight_utils.py:312] Time spent downloading weights for unsloth/Qwen3-4B-Thinking-2507: 187.033162 seconds

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

INFO 09-12 13:19:06 [default_loader.py:262] Loading weights took 30.81 seconds
INFO 09-12 13:19:06 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 09-12 13:19:08 [model_runner.py:1112] Model loading took 7.7296 GiB and 218.631993 seconds
INFO 09-12 13:19:19 [worker.py:295] Memory profiling takes 10.17 seconds
INFO 09-12 13:19:19 [worker.py:295] the current vLLM instance can use total_gpu_memory (14.74GiB) x gpu_memory_utilization (0.89) = 13.14GiB
INFO 09-12 13:19:19 [worker.py:295] model weights take 7.73GiB; non_torch_memory takes 0.03GiB; PyTorch activation peak memory takes 1.05GiB; the rest of the memory reserved for KV Cache is 4.33GiB.
INFO 09-12 13:19:21 [executor_base.py:114] # cuda blocks: 1971, # CPU blocks: 0
INFO 09-12 13:19:21 [executor_base.py:119] Maximum concurrency for 2048 tokens per request: 15.40x
INFO 09-12 13:19:21 [vllm_utils.py:695] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 09-12 13:19:21 [model_runner.py:1383] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/27 [00:00<?, ?it/s]

INFO 09-12 13:19:41 [model_runner.py:1535] Graph capturing finished in 20 secs, took 0.31 GiB
INFO 09-12 13:19:41 [vllm_utils.py:702] Unsloth: Patched vLLM v0 graph capture finished in 20 secs.
INFO 09-12 13:19:42 [llm_engine.py:417] init engine (profile, create kv cache, warmup model) took 34.68 seconds
INFO 09-12 13:19:43 [llm.py:298] Supported_tasks: ['generate']
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'post_feedforward_layernorm']
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'post_feedforward_layernorm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2025.9.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

### GRPO chat template
Since we're using a base model, we should set a chat template. You can make your own chat template as well!
1. DeepSeek uses `<think>` and `</think>`, but this is **not** necessary - you can customize it however you like!
2. A `system_prompt` is recommended to at least guide the model's responses.

In [4]:
reasoning_start = "<think>" # Acts as <think>
reasoning_end   = "</think>"   # Acts as </think>
# solution_start  = "<SOLUTION>"
# solution_end    = "</SOLUTION>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution after {reasoning_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <think> and </think>.\nThen, provide your solution after </think>'

We create a simple chat template below. Notice `add_generation_prompt` includes prepending `<start_working_out>` to guide the model to start its reasoning process.

In [5]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "qwen3-thinking",
)

Let's see how our chat template behaves on an example:

In [6]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}2"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

'<|im_start|>user\nWhat is 1+1?<|im_end|>\n<|im_start|>assistant\n2<|im_end|>\n<|im_start|>user\nWhat is 2+2?<|im_end|>\n<|im_start|>assistant\n<think>\n'

### Pre fine-tuning for formatting
We now use a subset of NVIDIA's [Open Math Reasoning dataset](https://huggingface.co/datasets/nvidia/OpenMathReasoning) which was filtered to only include high quality DeepSeek R1 traces.

We'll only filter ~59 or so examples to first "prime" / pre fine-tune the model to understand our custom GRPO formatting.

In [7]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("FreedomIntelligence/medical-o1-reasoning-SFT","zh", split = "train")
dataset = dataset.to_pandas()[
    ["Question", "Complex_CoT", "Response"]
]

dataset = dataset[
    dataset["Complex_CoT"].notna() &
    dataset["Response"].notna()
]

README.md: 0.00B [00:00, ?B/s]

medical_o1_sft_Chinese.json:   0%|          | 0.00/50.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20171 [00:00<?, ? examples/s]

We have to format the dataset to follow our GRPO style formatting:

In [8]:
def format_dataset(x):
    expected_answer = x["Response"]
    problem = x["Question"]

    # Remove generated <think> and </think>
    thoughts = x["Complex_CoT"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
          expected_answer
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

Check to see if it worked:

In [9]:
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

'<|im_start|>system\nYou are given a problem.\nThink about the problem and provide your working out.\nPlace it between <think> and </think>.\nThen, provide your solution after </think><|im_end|>\n<|im_start|>user\n根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？<|im_end|>\n<|im_start|>assistant\n<think>\n这个小孩子在夏天头皮上长了些小结节，一直都没好，后来变成了脓包，流了好多脓。想想夏天那么热，可能和湿热有关。才一岁的小孩，免疫力本来就不强，夏天的湿热没准就侵袭了身体。\n\n用中医的角度来看，出现小结节、再加上长期不愈合，这些症状让我想到了头疮。小孩子最容易得这些皮肤病，主要因为湿热在体表郁结。\n\n但再看看，头皮下还有空洞，这可能不止是简单的头疮。看起来病情挺严重的，也许是脓肿没治好。这样的情况中医中有时候叫做禿疮或者湿疮，也可能是另一种情况。\n\n等一下，头皮上的空洞和皮肤增厚更像是疾病已经深入到头皮下，这是不是说明有可能是流注或瘰疬？这些名字常描述头部或颈部的严重感染，特别是有化脓不愈合，又形成通道或空洞的情况。\n\n仔细想想，我怎么感觉这些症状更贴近瘰疬的表现？尤其考虑到孩子的年纪和夏天发生的季节性因素，湿热可能是主因，但可能也有火毒或者痰湿造成的滞留。\n\n回到基本的症状描述上看，这种长期不愈合又复杂的状况，如果结合中医更偏重的病名，是不是有可能是涉及更深层次的感染？\n\n再考虑一下，这应该不是单纯的瘰疬，得仔细分析头皮增厚并出现空洞这样的严重症状。中医里头，这样的表现可能更符合‘蚀疮’或‘头疽’。这些病名通常描述头部严重感染后的溃烂和组织坏死。\n\n看看季节和孩子的体质，夏天又湿又热，外邪很容易侵入头部，对孩子这么弱的免疫系统简直就是挑战。头疽这个病名听起来真是切合，因为它描述的感染严重，溃烂到出现空洞。\n\n不过，仔细琢磨后发现，还有个病名似乎更为合适，叫做‘蝼蛄疖’，这病在中医里专指像这种严重感染并伴有深部空洞的情况。它也涵盖了化脓和皮肤增厚这些症状。\n\n哦，该不会是夏季湿热，导致湿毒入侵，孩子的体质不能御，其病情发展成这样的感染？综合分析后我觉得‘蝼蛄疖’这个病名真是相当符合。\n</think>\n\n从中医的角度来看，你所描述的症状符合“蝼蛄疖”的病症。这种病症通常发生在头皮，表现为多处结节，溃破流脓，形成空洞，患处皮肤增厚且长期不愈合。湿热较重的夏季更容易导致这种病症的发展，特别是在免疫力较弱的儿童身上。建议结合中医的清热解毒、祛湿消肿的治疗方法进行处理，并配合专业的医疗建议进行详细诊断和治疗。<|im_end|>\n'

Let's truncate the pre fine-tuning dataset to `max_seq_length/2` since we don't want too long reasoning traces.

Note this might take 2 minutes!

In [ ]:
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

dataset = dataset.loc[dataset["N"] <= max_seq_length/2].copy()
dataset.shape

We then tokenize the messages and convert it to a Hugging Face compatible dataset format:

In [10]:
from datasets import Dataset

dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['Question', 'Complex_CoT', 'Response', 'Messages', 'text'],
    num_rows: 20171
})

Let's now pre fine-tune the model so it follows our custom GRPO formatting!

In [11]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4, # Use GA to mimic batch size!
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        learning_rate = 2e-5, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        max_steps=600,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/20171 [00:00<?, ? examples/s]

In [12]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 20,171 | Num Epochs = 1 | Total steps = 600
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=600, training_loss=1.7393054556846619, metrics={'train_runtime': 2346.6892, 'train_samples_per_second': 1.023, 'train_steps_per_second': 0.256, 'total_flos': 3.488797235596493e+16, 'train_loss': 1.7393054556846619, 'epoch': 0.11898269793267563})

Let's check if the model has learnt to follow the custom format:

In [13]:
text = tokenizer.apply_chat_template(
    dataset[0]["Messages"][:2],
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    temperature = 0,
    max_new_tokens = 1024,
    streamer = TextStreamer(tokenizer, skip_prompt = False),
)

<|im_start|>system
You are given a problem.
Think about the problem and provide your working out.
Place it between <think> and </think>.
Then, provide your solution after </think><|im_end|>
<|im_start|>user
根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？<|im_end|>
<|im_start|>assistant
<think>
这个1岁的小孩在夏天头皮上长了很多小结节，而且这些结节一直不愈合，现在变得很大，像梅子一样，还破了流脓。这听起来很严重，而且这些结节在头皮下还形成了空洞，皮肤也变厚了。嗯，这让我想到可能是某种感染或者慢性炎症。

在中医里，头皮上的问题通常和风、湿、热这些因素有关。特别是夏天，湿热容易上火，所以这些结节可能和湿热有关。不过，这些结节一直不愈合，而且变得很大，这让我想到是不是有更深层的问题，比如湿热积聚，或者有其他因素在作怪。

再想想，这些结节在头皮下形成空洞，皮肤增厚，这让我想到可能是某种慢性感染，比如湿疮或者湿疹。湿疮在中医里通常和湿热有关，而且会形成结节和溃烂。

不过，这些结节一直不愈合，而且变得很大，这让我想到是不是有更严重的感染，比如湿毒。湿毒在中医里通常表现为皮肤上的结节、溃烂，而且会形成空洞，这和这个小孩的症状很吻合。

嗯，再仔细想想，湿毒在中医里确实常表现为皮肤上的结节、溃烂，而且会形成空洞，这和这个小孩的症状很吻合。所以，我觉得这个小孩的病症在中医里可能是湿毒。

不过，再想想，湿毒通常会伴随其他症状，比如发热、口渴等。这个小孩的症状中没有提到这些，所以可能不是湿毒。

再考虑一下，湿热在中医里通常表现为皮肤上的结节、溃烂，而且会形成空洞，这和这个小孩的症状很吻合。而且，湿热在夏天更容易出现，这也符合这个小孩在夏季发病的情况。

嗯，再仔细想想，湿热在中医里确实常表现为皮肤上的结节、溃烂，而且会形成空洞，这和这个小孩的症状很吻合。而且，湿热在夏天更容易出现，这也符合这个小孩在夏季发病的情况。

所以，我觉得这个小孩的病症在中医里可能是湿热。嗯，这个结论看起来合理，符合所有症状和季节因素。
</think>

根据描述，这个1岁的小孩在夏季头皮上出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这些症状在中医中通常与湿热有关。湿热在中医里常表现为皮肤上的结节、溃烂，且会形成空洞，这与小孩的症状非常吻合。此外，湿热在夏季更容易出现，这也符合这个小孩在夏季发病的情况。因此，这个小孩的病症在中医中很可能是湿热。<|im_end|>

Yes it did follow the formatting! Great! Let's remove some items before the GRPO step

In [14]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

1336

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [15]:
from datasets import load_dataset
dataset = load_dataset("FreedomIntelligence/medical-o1-reasoning-SFT", "zh", split = "train")
dataset

Dataset({
    features: ['Question', 'Complex_CoT', 'Response'],
    num_rows: 20171
})

Let's look at the first row:

In [16]:
dataset[0]["Question"]

'根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？'

In [17]:
dataset[0]["Response"]

'从中医的角度来看，你所描述的症状符合“蝼蛄疖”的病症。这种病症通常发生在头皮，表现为多处结节，溃破流脓，形成空洞，患处皮肤增厚且长期不愈合。湿热较重的夏季更容易导致这种病症的发展，特别是在免疫力较弱的儿童身上。建议结合中医的清热解毒、祛湿消肿的治疗方法进行处理，并配合专业的医疗建议进行详细诊断和治疗。'

In GSM8K, ee notice all answers like about have a ####, so we extract it. But for the Open R1 dataset, we can skip the below.

In [18]:
def extract_hash_answer(text):
    if "####" in text:
        return text.split("####")[1].strip()
    return None
extract_hash_answer(dataset[0]["Response"])

'从中医的角度来看，你所描述的症状符合“蝼蛄疖”的病症。这种病症通常发生在头皮，表现为多处结节，溃破流脓，形成空洞，患处皮肤增厚且长期不愈合。湿热较重的夏季更容易导致这种病症的发展，特别是在免疫力较弱的儿童身上。建议结合中医的清热解毒、祛湿消肿的治疗方法进行处理，并配合专业的医疗建议进行详细诊断和治疗。'

Let's map the dataset! and see the first row:

In [19]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["Question"]},
    ],
    "answer": extract_hash_answer(x["Response"]),
})
dataset[0]

Map:   0%|          | 0/20171 [00:00<?, ? examples/s]

{'Question': '根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？',
 'Complex_CoT': '这个小孩子在夏天头皮上长了些小结节，一直都没好，后来变成了脓包，流了好多脓。想想夏天那么热，可能和湿热有关。才一岁的小孩，免疫力本来就不强，夏天的湿热没准就侵袭了身体。\n\n用中医的角度来看，出现小结节、再加上长期不愈合，这些症状让我想到了头疮。小孩子最容易得这些皮肤病，主要因为湿热在体表郁结。\n\n但再看看，头皮下还有空洞，这可能不止是简单的头疮。看起来病情挺严重的，也许是脓肿没治好。这样的情况中医中有时候叫做禿疮或者湿疮，也可能是另一种情况。\n\n等一下，头皮上的空洞和皮肤增厚更像是疾病已经深入到头皮下，这是不是说明有可能是流注或瘰疬？这些名字常描述头部或颈部的严重感染，特别是有化脓不愈合，又形成通道或空洞的情况。\n\n仔细想想，我怎么感觉这些症状更贴近瘰疬的表现？尤其考虑到孩子的年纪和夏天发生的季节性因素，湿热可能是主因，但可能也有火毒或者痰湿造成的滞留。\n\n回到基本的症状描述上看，这种长期不愈合又复杂的状况，如果结合中医更偏重的病名，是不是有可能是涉及更深层次的感染？\n\n再考虑一下，这应该不是单纯的瘰疬，得仔细分析头皮增厚并出现空洞这样的严重症状。中医里头，这样的表现可能更符合‘蚀疮’或‘头疽’。这些病名通常描述头部严重感染后的溃烂和组织坏死。\n\n看看季节和孩子的体质，夏天又湿又热，外邪很容易侵入头部，对孩子这么弱的免疫系统简直就是挑战。头疽这个病名听起来真是切合，因为它描述的感染严重，溃烂到出现空洞。\n\n不过，仔细琢磨后发现，还有个病名似乎更为合适，叫做‘蝼蛄疖’，这病在中医里专指像这种严重感染并伴有深部空洞的情况。它也涵盖了化脓和皮肤增厚这些症状。\n\n哦，该不会是夏季湿热，导致湿毒入侵，孩子的体质不能御，其病情发展成这样的感染？综合分析后我觉得‘蝼蛄疖’这个病名真是相当符合。',
 'Response': '从中医的角度来看，你所描述的症状符合“蝼蛄疖”的病症。这种病症通常发生在头皮，表现为多处结节，溃破流脓，形成空洞，患处皮肤增厚且长期不愈合。湿热较重的夏季更容易导致这种病症的发展，特别是在免疫力较弱的儿童身上。建议结合中医的清热解毒、祛湿消肿的治疗方法进行处理，并配合专业的医疗建议进行详细诊断和治疗。',
 'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <think> and </think>.\nThen, provide your solution after </think>',
   'role': 'system'},
  {'content': '根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？',
   'role': 'user'}],
 'answer': '从中医的角度来看，你所描述的症状符合“蝼蛄疖”的病症。这种病症通常发生在头皮，表现为多处结节，溃破流脓，形成空洞，患处皮肤增厚且长期不愈合。湿热较重的夏季更容易导致这种病症的发展，特别是在免疫力较弱的儿童身上。建议结合中医的清热解毒、祛湿消肿的治疗方法进行处理，并配合专业的医疗建议进行详细诊断和治疗。'}

We create a regex format to match the reasoning sections and answers:

In [20]:
import re

# Add optional EOS token matching
# solution_end_regex = r"</SOLUTION>[\s]{0,}" + \
#     "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}(.*)", # Match </think> followed by any characters (greedy)
    flags = re.MULTILINE | re.DOTALL
)
match_format

re.compile(r'</think>(.*)', re.MULTILINE|re.DOTALL|re.UNICODE)

We verify it works:

In [21]:
match_format.findall(
    "Let me think!</think>"\
    f"<SOLUTION>\n2\n</SOLUTION>",
)

['<SOLUTION>\n2\n</SOLUTION>']

In [22]:
match_format.findall(
    "<think>Let me think!</think>"\
    f"<SOLUTION>  2  </SOLUTION>\n\n",
)

['<SOLUTION>  2  </SOLUTION>\n\n']

We now want to create a reward function to match the format exactly - we reward it with 3 points if it succeeds:

In [23]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

If it fails, we want to reward the model if it at least follows the format partially, by counting each symbol:

In [24]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

In [25]:
%pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.107.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

Finally, we want to extract the generated answer, and reward or penalize it! We also reward it based on how close the answer is to the true one via ratios:

In [ ]:
# Correctness rewards (aligned with Qwen3-SFT-GRPO.py)
def check_answer(prompts, completions, answer, **kwargs):
    responses = [completion[0]["content"] for completion in completions]
    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None         for r in responses
    ]
    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        if true_answer is None:
            scores.append(-2.0)
            continue
        if guess == true_answer:
            score += 5.0
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            try:
                ratio = float(guess) / float(true_answer)
                if ratio >= 0.9 and ratio <= 1.1:
                    score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2:
                    score += 1.5
                else:
                    score -= 2.5
            except:
                score -= 4.5
        scores.append(score)
    return scores

match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)

PRINTED_TIMES = 0
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]
    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None         for r in responses
    ]
    scores = []
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        true_answer_display = answer[0] if answer and answer[0] is not None else "N/A"
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{true_answer_display}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer_item in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        if true_answer_item is None:
            scores.append(-2.5)
            continue
        try:
            true_answer_val = float(true_answer_item.strip())
            guess_val = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess_val == true_answer_val else -1.5)
        except:
            scores.append(0)
            continue
    return scores

In [27]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/20171 [00:00<?, ? examples/s]

<|im_start|>system
You are given a problem.
Think about the problem and provide your working out.
Place it between <think> and </think>.
Then, provide your solution after </think><|im_end|>
<|im_start|>user
根据描述，一个1岁的孩子在夏季头皮出现多处小结节，长期不愈合，且现在疮大如梅，溃破流脓，口不收敛，头皮下有空洞，患处皮肤增厚。这种病症在中医中诊断为什么病？<|im_end|>
<|im_start|>assistant
<think>

Map:   0%|          | 0/20171 [00:00<?, ? examples/s]

Max Length =  154

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [34]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.0,
    top_p = 0.95,
    top_k = 20,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GSPOConfig, GSPOTrainer
training_args = GSPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 0.6,
    learning_rate = 5e-6,
    weight_decay = 0.01,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",
    reward_weights= [0.05, 0.05, 0.8, 0.1],
)

Unsloth: We now expect `per_device_train_batch_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 4

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [ ]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GSPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 18,161 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

================================================================================
Step 0 - Batch Evaluation Sample (Prompt 0 of 4)
Question: 一位28岁的女性患者出现尿频、尿急、尿痛2天，无发热及腰痛，既往无类似发作。查体显示双肾区无叩击痛，血液白细胞计数为5.4×10^9/L，尿液白细胞为30～40/HP，红细胞为10～15/HP，尿亚硝酸盐呈阳性。对于这种情况下的患者，标准的抗感染治疗应持续多长时间？
True Answer: 对于这种情况下的患者，基于目前的诊断和推荐的指南，标准的抗感染治疗通常持续3天。对于年轻、健康的女性而言，在尿路感染的情况下，短期疗程（如3天）的抗生素治疗通常非常有效，这有助于减少抗生素的不必要使用和潜在的副作用。

=== All Generations for All Prompts (4 prompts, 4 total generations) ===

--- Prompt 0 (1 generations) ---
Question: 一位28岁的女性患者出现尿频、尿急、尿痛2天，无发热及腰痛，既往无类似发作。查体显示双肾区无叩击痛，血液白细胞计数为5.4×10^9/L，尿液白细胞为30～40/HP，红细胞为10～15/HP，尿亚硝酸盐呈阳性。对于这种情况下的患者，标准的抗感染治疗应持续多长时间？
True Answer: 对于这种情况下的患者，基于目前的诊断和推荐的指南，标准的抗感染治疗通常持续3天。对于年轻、健康的女性而言，在尿路感染的情况下，短期疗程（如3天）的抗生素治疗通常非常有效，这有助于减少抗生素的不必要使用和潜在的副作用。

  Generation 1/1:
    Extracted Answer: 根据描述的症状和检查结果，这位28岁的女性患者很可能患有急性膀胱炎。急性膀胱炎通常由大肠杆菌引起，并且常见于女性。标准的抗感染治疗通常为3到7天，具体时间取决于患者的症状变化和对治疗的反应。此外，多喝水有助于冲洗尿路，减少细菌的停留。如果症状没有改善，或者有复发，可能需要调整抗生素种类或者延长疗程。建议在治疗期间密切关注症状变化和尿液检查结果，以决定是否需要调整治疗方案。
    Assigned Score: 0.5

--- Prompt 1 (1 generations) ---
Question: 一位28岁的女性患者出现尿频、尿急、尿痛2天，无发热及腰痛，既往无类似发作。查体显示双肾区无叩击痛，血液白细胞计数为5.4×10^9/L，尿液白细胞为30～40/HP，红细胞为10～15/HP，尿亚硝酸盐呈阳性。对于这种情况下的患者，标准的抗感染治疗应持续多长时间？
True Answer: 对于这种情况下的患者，基于目前的诊断和推荐的指南，标准的抗感染治疗通常持续3天。对于年轻、健康的女性而言，在尿路感染的情况下，短期疗程（如3天）的抗生素治疗通常非常有效，这有助于减少抗生素的不必要使用和潜在的副作用。

  Generation 1/1:
    Extracted Answer: 对于这位28岁的女性患者，她的症状和检查结果提示急性膀胱炎的可能性较大。急性膀胱炎通常由尿路细菌感染引起，而尿亚硝酸盐阳性是细菌感染的标志。

在治疗上，对于急性细菌性膀胱炎，标准的抗感染治疗通常为1到2周。然而，具体治疗时长应由医生根据患者的具体情况来决定，包括症状的严重程度、对治疗的反应以及尿液检查的结果等。

考虑到患者的症状和检查结果，没有严重感染迹象，一般情况下，1周的抗生素治疗可能就足够了。但是，医生会根据个体情况和治疗反应进行调整，以确保感染彻底清除。

所以，标准的抗感染治疗通常持续时间为1到2周，但具体时间由医生根据患者的具体情况来决定。
    Assigned Score: -0.5

--- Prompt 2 (1 generations) ---
Question: 一位28岁的女性患者出现尿频、尿急、尿痛2天，无发热及腰痛，既往无类似发作。查体显示双肾区无叩击痛，血液白细胞计数为5.4×10^9/L，尿液白细胞为30～40/HP，红细胞为10～15/HP，尿亚硝酸盐呈阳性。对于这种情况下的患者，标准的抗感染治疗应持续多长时间？
True Answer: 对于这种情况下的患者，基于目前的诊断和推荐的指南，标准的抗感染治疗通常持续3天。对于年轻、健康的女性而言，在尿路感染的情况下，短期疗程（如3天）的抗生素治疗通常非常有效，这有助于减少抗生素的不必要使用和潜在的副作用。

  Generation 1/1:
    Extracted Answer: 对于这位28岁的女性患者，根据她的症状和检查结果，可以诊断为急性尿路感染。通常情况下，对于没有严重并发症的急性尿路感染，抗生素治疗的疗程建议为3到7天。在她的案例中，由于症状较轻且无发热、腰痛等全身症状，三天的疗程可能是合适的。然而，具体的治疗时长还应根据患者的具体情况和医生的建议来确定，以确保有效控制感染并防止复发。建议在治疗期间定期复查尿液，以评估治疗效果。
    Assigned Score: 0.5

--- Prompt 3 (1 generations) ---
Question: 一位28岁的女性患者出现尿频、尿急、尿痛2天，无发热及腰痛，既往无类似发作。查体显示双肾区无叩击痛，血液白细胞计数为5.4×10^9/L，尿液白细胞为30～40/HP，红细胞为10～15/HP，尿亚硝酸盐呈阳性。对于这种情况下的患者，标准的抗感染治疗应持续多长时间？
True Answer: 对于这种情况下的患者，基于目前的诊断和推荐的指南，标准的抗感染治疗通常持续3天。对于年轻、健康的女性而言，在尿路感染的情况下，短期疗程（如3天）的抗生素治疗通常非常有效，这有助于减少抗生素的不必要使用和潜在的副作用。

  Generation 1/1:
    Extracted Answer: 对于这位28岁的女性患者，她的症状和尿液检查结果表明她可能患有急性单纯性膀胱炎，这是一种常见的尿路感染。根据医学指南，急性单纯性膀胱炎的标准抗感染治疗通常为3天。然而，需要注意的是，如果患者的症状没有完全消失，可能需要延长治疗时间。因此，在治疗过程中，应密切观察患者的症状变化，以确保感染完全消退。
    Assigned Score: 2.0

Full Scores List for this batch (4 total): [0.5, -0.5, 0.5, 2.0]
================================================================================

In [ ]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

In [ ]:
model.save_lora("grpo_saved_lora")

In [ ]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

In [ ]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_16bit", token = "")

# Merge to 4bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_4bit", token = "")

# Just LoRA adapters
if False:
    model.save_pretrained("model")
    tokenizer.save_pretrained("model")
if False:
    model.push_to_hub("hf/model", token = "")
    tokenizer.push_to_hub("hf/model", token = "")

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("hf/model", tokenizer, token = "")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "f16", token = "")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q4_k_m", token = "")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "hf/model", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "",
    )